In [2]:
import numpy as np

In [2]:
x = np.array([1,2,3])
x.__class__

numpy.ndarray

In [3]:
x.shape

(3,)

In [4]:
x.ndim

1

In [6]:
W = np.array([[1,2,3], [4,5,6]])

In [7]:
W.shape

(2, 3)

In [8]:
W.ndim

2

In [10]:
A = np.array([[1,2], [3,4]])
B= np.array([10,20])

In [11]:
A*B

array([[10, 40],
       [30, 80]])

In [12]:
a= np.array([1,2,3])
b= np.array([4,5,6])

In [13]:
np.dot(a,b)

32

In [14]:
np.matmul(A,B)

array([ 50, 110])

In [15]:
np.matmul(a,b)

32

In [16]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6], [7,8]])

In [17]:
np.matmul(A,B)

array([[19, 22],
       [43, 50]])

In [18]:
W1 = np.random.randn(2,4)
b1 = np.random.randn(4)
x = np.random.randn(10, 2)
h = np.matmul(x, W1) + b1

In [19]:
W1

array([[ 0.86769304,  0.62555118, -1.53776194, -0.12438233],
       [ 0.36287121, -0.12903376, -1.56019734,  0.80387177]])

In [20]:
b1

array([-1.0044566 ,  1.76907381,  0.20100594, -1.86813131])

In [21]:
h

array([[-0.12629743,  1.63295581, -3.16117908, -0.30867463],
       [-0.7975305 ,  1.92959848, -0.13908458, -1.92264877],
       [-0.87105313,  1.3658232 , -1.2079128 , -0.79301856],
       [-1.02439101,  1.92905196,  0.64565263, -2.24727143],
       [ 0.20472995,  2.88126325, -1.37747971, -2.5682743 ],
       [-0.97220722,  2.22905127,  1.1691519 , -2.82961903],
       [-0.07009409,  2.43985392, -1.46156728, -1.99585806],
       [-2.49163429,  0.58733676,  2.57939189, -1.41486494],
       [-1.79454296,  1.28146785,  1.79373038, -1.93452542],
       [-0.99911626,  1.79552184,  0.24459451, -1.91840872]])

In [22]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [23]:
a = sigmoid(h)

In [24]:
a

array([[0.46846755, 0.83657415, 0.04065304, 0.42343828],
       [0.31055402, 0.87320497, 0.4652848 , 0.12756648],
       [0.29503522, 0.79670449, 0.23007056, 0.31152089],
       [0.26417297, 0.87314445, 0.65603012, 0.09558509],
       [0.55100446, 0.9469124 , 0.20141408, 0.07120835],
       [0.27444077, 0.90282816, 0.76299168, 0.05574445],
       [0.48248365, 0.91981631, 0.18822773, 0.11963849],
       [0.07644673, 0.64275384, 0.92952344, 0.19546786],
       [0.14251665, 0.78269953, 0.85738402, 0.12625053],
       [0.26911521, 0.85760294, 0.56084558, 0.12803912]])

In [25]:
W2 = np.random.rand(4,3)
b2 = np.random.rand(3)
s = np.matmul(a, W2) + b2

In [26]:
b2

array([0.7430676 , 0.98411972, 0.98764431])

In [1]:
import numpy as np

class Sigmoid:
    def __init__(self):
        self.params = []
    
    def forward(self, x):
        return 1/(1+np.exp(-x))

class Affine:
    def __init__(self, W, b):
        self.params = [W, b]
        
    def forward(self, x):
        W, b = self.params
        out = np.matmul(x, W) + b
        return out

In [2]:
class TwoLayerNet:
    def __init__(self, input_size, hidden_size, output_size):
        I, H, O = input_size, hidden_size, output_size
        
        W1 = np.random.randn(I, H)
        b1 = np.random.randn(H)
        W2 = np.random.randn(H, O)
        b2 = np.random.randn(O)
        
        self.layers = [
            Affine(W1, b1),
            Sigmoid(),
            Affine(W2, b2)
        ]
        
        self.params = []
        for layer in self.layers:
            self.params += layer.params
            
    def predict(self, x):
        for layer in self.layers:
            x = layer.forward(x)
        return x

In [4]:
x = np.random.randn(10, 2)
model = TwoLayerNet(2, 4, 3)
s = model.predict(x)

In [6]:
x

array([[-0.06534736,  0.47399393],
       [-1.42765241,  0.15236043],
       [ 1.29742257, -2.00045657],
       [-0.50562758,  1.01694183],
       [ 0.21470399,  1.30412981],
       [ 0.29413042, -1.02282653],
       [ 1.21550427,  0.08716375],
       [-0.17300011,  1.53849709],
       [ 1.76611032,  0.35241496],
       [ 0.327904  , -0.81570158]])

In [7]:
s

array([[-0.79203741,  0.26265078,  0.58459626],
       [-0.68791907,  0.58823541, -0.35111813],
       [-0.62703833,  0.58491955,  0.85850873],
       [-0.81565818,  0.25538169,  0.39860276],
       [-0.82347159,  0.19851857,  0.9171187 ],
       [-0.66127996,  0.58891797,  0.42069344],
       [-0.78518628,  0.18316974,  1.2667586 ],
       [-0.83253337,  0.21805246,  0.70953129],
       [-0.79913409,  0.147133  ,  1.50333955],
       [-0.68064632,  0.5390277 ,  0.49690848]])

In [8]:
class MatMul:
    def __init__(self, W):
        self.params = [W]
        self.grads = [np.zeros_like(W)]
        self.x = None
        
    def forward(self, x):
        W, = self.params
        out = np.matmul(x, W)
        self.x = x
        
        return dx
    
    def backward(self, dout):
        W, = self.params
        dx = np.matmul(dout, W.T)
        dW = np.matmul(self.x.T, dout)
        self.grads[0][...] = dW
        
        return dx

In [9]:
class Sigmoid:
    def __init__(self):
        self.params, self.grads = [], []
        self.out = None
        
    def forward(self, x):
        out = 1/(1+np.exp(-x))
        self.out = out
        return out
    
    def backward(self, dout):
        dx = dout * (1.0 - self.out) * self.out
        return dx

In [10]:
class Affine:
    def __init__(self, W, b):
        self.params = [W, b]
        self.grads = [np.zeros_like(W), np.zeros_like(b)]
        self.x = None
        
    def forward(self, x):
        W, b = self.params
        out = np.matmul(x, W) + b
        self.x = x
        return out
    
    def backward(self, x):
        W, b = self.params
        dx = np.matmul(dout, W.T)
        dW = np.matmul(self.x.T, dout)
        db = np.sum(dout, axis = 0)
        
        self.grads[0][...] = dW
        self.grads[1][...] = db
        return dx

In [11]:
class SGD:
    def __init__(self, lr=0.01):
        self.lr = lr
        
    def update(self, parmas, grads):
        for i in range(len(params)):
            params[i] -= self.lr*grads[i]

In [ ]:
model = TwoLayerNet(...)
optimizer = SGD()

for i in range(10000):
    ...
    x_batch, t_batch = get_mini_batch(...)
    loss = model.forward(x_batch, t_batch)
    model.backward()
    optimizer.update(model.params, model.grads)
    ...

In [1]:
text = 'you say goodbye and i say hello'
words = text.split(' ')

word_to_id = {}
id_to_word = {}

for word in words:
    if word not in word_to_id:
        new_id = len(word_to_id)
        word_to_id[word] = new_id
        id_to_word[new_id] = word

In [2]:
word_to_id

{'you': 0, 'say': 1, 'goodbye': 2, 'and': 3, 'i': 4, 'hello': 5}

In [3]:
id_to_word

{0: 'you', 1: 'say', 2: 'goodbye', 3: 'and', 4: 'i', 5: 'hello'}

In [4]:
import numpy as np

corpus = [word_to_id[w] for w in words]
corpus = np.array(corpus)

In [5]:
corpus

array([0, 1, 2, 3, 4, 1, 5])

In [6]:
def create_co_matrix(corpus, vocab_size, window_size = 1):
    corpus_size = len(corpus)
    co_matrix = np.zeros((vocab_size, vocab_size), dtype=np.int32)
    
    for idx, word_id in enumerate(corpus):
        for i in range(1, window_size + 1):
            left_idx = idx - i
            right_idx = idx + i
            
            if left_idx >= 0:
                left_word_id = corpus[left_idx]
                co_matrix[word_id, left_word_id] += 1
                
            if right_idx < corpus_size:
                right_word_id = corpus[right_idx]
                co_matrix[word_id, right_word_id] += 1
                
        return co_matrix

In [3]:
def cos_similarity(x, y):
    
    nx = x/np.sqrt(np.sum(x**2))
    ny = y/np.sqrt(np.sum(y**2))
    
    return np.dot(nx, ny)

In [ ]:
import sys
sys.path.append('')

In [1]:
import numpy as np

x = np.array([100, -20, 2])
print(x.argsort())

[1 2 0]


In [2]:
(-x).argsort()

array([0, 2, 1])

In [ ]:
import sys

sys.path.append('..')
from common.util import 